# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='The full official company name', max_length=120)),
                ('short_title', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_title'],
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='The full official company name', max_length=120)),
                ('short_title', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_title'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='The full official company name', max_length=120)),
                ('short_title', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_title'],
            },
        ),
        migrations.CreateModel(
            name='CostBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='Work Item Title', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('profit', models.DecimalField(decimal_places=2, help_text='Profit percentage in decimal number. Example: 0.2 for 20%', max_digits=3)),
                ('overhead', models.DecimalField(decimal_places=2, help_text='Labour and equipment output', max_digits=3)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'full_title'],
                'verbose_name_plural': 'cost breakdowns',
                'verbose_name': 'cost breakdown',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=120)),
                ('short_title', models.CharField(blank=True, max_length=30, null=True)),
                ('rental_rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Current rental rate', max_digits=12, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_title', '-rental_rate', '-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('rental_rate', models.DecimalField(decimal_places=2, help_text='Equipment hourly rental rate', max_digits=8)),
                ('uf', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('costbreakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.CostBreakdown')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Equipment')),
            ],
            options={
                'ordering': ['costbreakdown', 'equipment', '-rental_rate'],
                'verbose_name_plural': 'equipment breakdowns',
                'verbose_name': 'equipment breakdown',
            },
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=120)),
                ('short_title', models.CharField(blank=True, max_length=30, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Current hourly rate', max_digits=12, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_title', '-hourly_rate', '-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='LabourBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('uf', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('costbreakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.CostBreakdown')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Labour')),
            ],
            options={
                'ordering': ['costbreakdown', 'labour', '-hourly_rate'],
                'verbose_name_plural': 'labour breakdowns',
                'verbose_name': 'labour breakdown',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=120)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Current market unit rate of material', max_digits=12, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_title', '-rate', '-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costbreakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.CostBreakdown')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Material')),
            ],
            options={
                'ordering': ['costbreakdown', 'material', '-rate'],
                'verbose_name_plural': 'material breakdowns',
                'verbose_name': 'material breakdown',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='The full official project title', max_length=120)),
                ('short_title', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(max_length=60)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Client')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Consultant')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Contractor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_title'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=60)),
                ('short_title', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['full_title'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Unit'),
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Project'),
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='unit',
            field=models.ForeignKey(help_text='Measurement unit for the cost breakdown', on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Unit'),
        ),
    ]
