# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='Equipment type catagory', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_title'],
                'verbose_name_plural': 'Equipment Catagories',
            },
        ),
        migrations.CreateModel(
            name='LabourCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='Labour type catagory', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_title'],
                'verbose_name_plural': 'Labour Catagories',
            },
        ),
        migrations.CreateModel(
            name='MaterialCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='Material type catagory', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_title'],
                'verbose_name_plural': 'Material Catagories',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdowns.LabourCatagory'),
        ),
        migrations.AddField(
            model_name='labour',
            name='labour_catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdowns.LabourCatagory'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdowns.MaterialCatagory'),
        ),
    ]
