# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0002_auto_20170720_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='Work type catagory for breakdown', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_title'],
                'verbose_name_plural': 'Breakdown Catagories',
            },
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='breakdown_catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdowns.BreakdownCatagory'),
        ),
    ]
