# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0003_auto_20170720_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='short_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
