# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0005_auto_20170721_2113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreakdownCatagory',
            new_name='CostBreakdownCatagory',
        ),
        migrations.RenameField(
            model_name='costbreakdown',
            old_name='breakdown_catagory',
            new_name='cost_breakdown_catagory',
        ),
    ]
