# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0006_auto_20170722_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costbreakdowncatagory',
            options={'ordering': ['full_title'], 'verbose_name_plural': 'Cost Breakdown Catagories'},
        ),
    ]
