# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0007_auto_20170722_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costbreakdown',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Project'),
        ),
    ]
