# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0009_auto_20170722_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbreakdown',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
