# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0012_auto_20170725_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['full_title', '-rental_rate', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='labour',
            options={'ordering': ['full_title', '-hourly_rate', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['full_title', '-rate', '-updated_at']},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='labour',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='material',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmentbreakdown',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentbreakdown',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labour',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labourbreakdown',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labourbreakdown',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='materialbreakdown',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialbreakdown',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(default='xxxx', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='consultant',
            field=models.CharField(default='xxxx', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='contractor',
            field=models.CharField(default='xxxx', max_length=120),
            preserve_default=False,
        ),
    ]
