# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0013_auto_20170726_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
    ]
