# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0014_remove_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialbreakdown',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Unit'),
            preserve_default=False,
        ),
    ]
