# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0016_auto_20170730_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costbreakdown',
            options={'ordering': ['project', 'full_title'], 'permissions': (('download_cost_breakdown', 'Can download cost breakdown in excel and pdf'), ('admin_cost_breakdown', 'Can administer main cost breakdown libraries')), 'verbose_name': 'cost breakdown', 'verbose_name_plural': 'cost breakdowns'},
        ),
    ]
