# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0019_auto_20170730_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costbreakdown',
            options={'ordering': ['project', 'full_title'], 'permissions': (('download_cost_breakdown', 'Can download cost breakdown in excel and pdf'), ('manage_cost_breakdown', 'Can manage own cost breakdown')), 'verbose_name': 'cost breakdown', 'verbose_name_plural': 'cost breakdowns'},
        ),
    ]
