# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0020_auto_20170730_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costbreakdown',
            name='overhead',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overhead percentage in decimal number. Example: 0.15 for 15%', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='costbreakdown',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profit percentage in decimal number. Example: 0.2 for 20%', max_digits=6, null=True),
        ),
    ]
