# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0021_auto_20170801_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costbreakdown',
            options={'ordering': ['project', 'full_title'], 'permissions': (('download_cost_breakdown', 'Can download cost breakdown in excel and pdf'), ('manage_cost_breakdown', 'Can manage own cost breakdown'), ('manage_library', 'Can manage standard cost breakdown library')), 'verbose_name': 'cost breakdown', 'verbose_name_plural': 'cost breakdowns'},
        ),
    ]
