# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0024_auto_20170803_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='The full official city title', max_length=60)),
                ('short_title', models.CharField(blank=True, help_text='Short unofficial city title. (Optional)', max_length=30, null=True)),
            ],
            options={
                'ordering': ['full_title'],
            },
        ),
    ]
