# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0026_auto_20170804_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labour',
            options={'ordering': ['labour_catagory', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='labourprice',
            options={'ordering': ['city', '-hourly_rate']},
        ),
        migrations.AddField(
            model_name='unit',
            name='html_title',
            field=models.CharField(blank=True, help_text='Unit with superscript tags. Eg. m3, m2...', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='short_title',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
