# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0027_auto_20170806_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourbreakdown',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
