# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0028_auto_20170816_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbreakdown',
            name='rental_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Equipment hourly rental rate', max_digits=8),
        ),
        migrations.AlterField(
            model_name='labourbreakdown',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
