# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0029_auto_20170816_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='costbreakdown',
            name='is_library',
            field=models.BooleanField(default=False),
        ),
    ]
