# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0034_accounttype_company_companymembership_usermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registered_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
