# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breakdowns', '0035_company_registered_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='Notification title', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['notification_group', 'notification_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='Notification group title', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_title'],
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='Notification type title', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_title'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(help_text='Number of days of the package offering')),
                ('max_members', models.IntegerField(help_text='Number of maximum number of membership per package')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['package_type', 'full_title', '-price'],
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_title'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_seen', 'user', '-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['full_title']},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['full_title', '-rental_rate', '-updated_at'], 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='labour',
            options={'ordering': ['labour_catagory', '-updated_at'], 'verbose_name_plural': 'Labour'},
        ),
        migrations.AlterModelOptions(
            name='librarybreakdowncatagory',
            options={'ordering': ['full_title'], 'verbose_name_plural': 'Library Cost Breakdown Catagories'},
        ),
        migrations.AlterModelOptions(
            name='standardbreakdown',
            options={'ordering': ['full_title', '-updated_at'], 'permissions': (('manage_library', 'Can manage standard breakdown library'), ('access_premium', 'Can access premium breakdowns')), 'verbose_name': 'Standard library breakdown', 'verbose_name_plural': 'Standard library breakdowns'},
        ),
        migrations.AlterModelOptions(
            name='standardlibrary',
            options={'ordering': ['full_title'], 'permissions': (('access_private', 'Can access private standard libraries'),), 'verbose_name': 'Standard Library', 'verbose_name_plural': 'Standard Libraries'},
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='price',
        ),
        migrations.AddField(
            model_name='standardbreakdown',
            name='is_premium',
            field=models.BooleanField(default=True, help_text='Does this cost breakdown is only available for paid users?'),
        ),
        migrations.AddField(
            model_name='standardlibrary',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdowns.Company'),
        ),
        migrations.AddField(
            model_name='standardlibrary',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Does cost breakdown catagory is private to a single company?'),
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.PackageType'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.NotificationGroup'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.NotificationType'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Package'),
            preserve_default=False,
        ),
    ]
