# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0035_company_registered_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardbreakdown',
            options={'ordering': ['full_title', '-updated_at'], 'permissions': (('manage_library', 'Can manage standard breakdown library'), ('access_premium', 'Can access premium breakdowns')), 'verbose_name': 'Standard library breakdown', 'verbose_name_plural': 'Standard library breakdowns'},
        ),
        migrations.AlterModelOptions(
            name='standardlibrary',
            options={'ordering': ['full_title'], 'permissions': (('access_private', 'Can access private standard libraries'),), 'verbose_name': 'Standard Library', 'verbose_name_plural': 'Standard Libraries'},
        ),
        migrations.AddField(
            model_name='standardbreakdown',
            name='is_premium',
            field=models.BooleanField(default=True, help_text='Does this cost breakdown is only available for paid users?'),
        ),
        migrations.AddField(
            model_name='standardlibrary',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdowns.Company'),
        ),
        migrations.AddField(
            model_name='standardlibrary',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Does cost breakdown catagory is private to a single company?'),
        ),
    ]
