# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0036_auto_20170829_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['full_title', '-rental_rate', '-updated_at'], 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='labour',
            options={'ordering': ['labour_catagory', '-updated_at'], 'verbose_name_plural': 'Labour'},
        ),
    ]
