# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breakdowns', '0036_auto_20170906_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid for membership (including VAT)', max_digits=12)),
                ('payment_date', models.DateField(help_text='Date where payment is completed by the registered company')),
            ],
            options={
                'ordering': ['-payment_date', 'company_membership'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='User Membership start date')),
                ('end_date', models.DateField(blank=True, help_text='User Membership end date', null=True)),
                ('approved', models.BooleanField(default=False, help_text='Approve user membership')),
            ],
            options={
                'ordering': ['-approved', '-end_date', 'user'],
            },
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid for membership (including VAT)', max_digits=12)),
                ('payment_date', models.DateField(help_text='Date where payment is completed by the registered user')),
                ('user_membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdowns.UserMembership')),
            ],
            options={
                'ordering': ['-payment_date', 'user_membership'],
            },
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.AddField(
            model_name='companymembership',
            name='approved',
            field=models.BooleanField(default=False, help_text='Approve company membership'),
        ),
        migrations.AddField(
            model_name='package',
            name='max_breakdowns',
            field=models.IntegerField(blank=True, help_text='Number of maximum number of cost breakdowns that can be generated per month', null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='company_membership',
            field=models.ForeignKey(blank=True, help_text='If user is an employee of a registered company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdowns.CompanyMembership'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Package'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companypayment',
            name='company_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdowns.CompanyMembership'),
        ),
    ]
