# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0037_auto_20170829_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(help_text='Number of days of the package offering')),
                ('max_members', models.IntegerField(help_text='Number of maximum number of membership per package')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['package_type', 'full_title', '-price'],
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_title'],
            },
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['full_title']},
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='price',
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.PackageType'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='package',
            field=models.ForeignKey(default='no', on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Package'),
            preserve_default=False,
        ),
    ]
