# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0037_auto_20170910_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymembership',
            name='end_date',
            field=models.DateField(blank=True, help_text='Membership end date', null=True),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='start_date',
            field=models.DateField(blank=True, help_text='Membership start date', null=True),
        ),
    ]
