# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0039_auto_20170910_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='start_date',
            field=models.DateField(blank=True, help_text='User Membership start date', null=True),
        ),
    ]
