# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0040_auto_20170910_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembership',
            name='registered_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
