# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0042_usermembership_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='default',
            field=models.BooleanField(default=False, help_text='Default package assigned to all new registered users intially'),
        ),
    ]
