# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0043_package_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='level',
            field=models.IntegerField(default=3, help_text='Level of the membership packages'),
            preserve_default=False,
        ),
    ]
