# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0046_auto_20170911_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Membership has/has not expired'),
        ),
    ]
