# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breakdowns', '0047_usermembership_is_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='Activity catagory for breakdown', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_title'],
            },
        ),
        migrations.CreateModel(
            name='LibraryBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(help_text='Work Item Title', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('methodology', models.TextField(blank=True, null=True, verbose_name='Work Methodology')),
                ('output', models.DecimalField(decimal_places=2, help_text='Labour and equipment output', max_digits=3)),
                ('is_premium', models.BooleanField(default=False, help_text='Does this cost breakdown is only available for paid users?')),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('activity_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.ActivityCatagory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['activity_catagory', 'full_title'],
            },
        ),
        migrations.CreateModel(
            name='LibraryEquipmentBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('uf', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Equipment')),
                ('library_breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.LibraryBreakdown')),
            ],
            options={
                'verbose_name': 'standard library equipment breakdown',
                'verbose_name_plural': 'standard library equipment breakdowns',
                'ordering': ['library_breakdown', 'equipment', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryLabourBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('uf', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Labour')),
                ('library_breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.LibraryBreakdown')),
            ],
            options={
                'verbose_name': 'standard library labour breakdown',
                'verbose_name_plural': 'standard library labour breakdowns',
                'ordering': ['library_breakdown', 'labour', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryMaterialBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('library_breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.LibraryBreakdown')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Material')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Unit')),
            ],
            options={
                'verbose_name': 'standard library material breakdown',
                'verbose_name_plural': 'standard library material breakdowns',
                'ordering': ['library_breakdown', 'material', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='standardbreakdown',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='standardbreakdown',
            name='library_breakdown_catagory',
        ),
        migrations.RemoveField(
            model_name='standardbreakdown',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='standardequipmentbreakdown',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='standardequipmentbreakdown',
            name='standard_breakdown',
        ),
        migrations.RemoveField(
            model_name='standardlabourbreakdown',
            name='labour',
        ),
        migrations.RemoveField(
            model_name='standardlabourbreakdown',
            name='standard_breakdown',
        ),
        migrations.RemoveField(
            model_name='standardmaterialbreakdown',
            name='material',
        ),
        migrations.RemoveField(
            model_name='standardmaterialbreakdown',
            name='standard_breakdown',
        ),
        migrations.RemoveField(
            model_name='standardmaterialbreakdown',
            name='unit',
        ),
        migrations.AlterModelOptions(
            name='standardlibrary',
            options={'ordering': ['library_package', 'full_title']},
        ),
        migrations.RemoveField(
            model_name='costbreakdown',
            name='cost_breakdown_catagory',
        ),
        migrations.RemoveField(
            model_name='standardlibrary',
            name='company',
        ),
        migrations.RemoveField(
            model_name='standardlibrary',
            name='is_private',
        ),
        migrations.AddField(
            model_name='standardlibrary',
            name='last_updated',
            field=models.DateField(null=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='standardlibrary',
            name='owners',
            field=models.CharField(blank=True, help_text='Owner/Owners or publishers of the library', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='standardlibrary',
            name='published_at',
            field=models.DateField(null=True, verbose_name='First Published'),
        ),
        migrations.AddField(
            model_name='standardlibrary',
            name='remark',
            field=models.TextField(blank=True, help_text='Special remarks on the library', null=True),
        ),
        migrations.AddField(
            model_name='standardlibrary',
            name='short_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='standardlibrary',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the library', null=True),
        ),
        migrations.AlterField(
            model_name='standardlibrary',
            name='full_title',
            field=models.CharField(help_text='Title of the library', max_length=100),
        ),
        migrations.DeleteModel(
            name='CostBreakdownCatagory',
        ),
        migrations.DeleteModel(
            name='LibraryBreakdownCatagory',
        ),
        migrations.DeleteModel(
            name='StandardBreakdown',
        ),
        migrations.DeleteModel(
            name='StandardEquipmentBreakdown',
        ),
        migrations.DeleteModel(
            name='StandardLabourBreakdown',
        ),
        migrations.DeleteModel(
            name='StandardMaterialBreakdown',
        ),
        migrations.AddField(
            model_name='librarybreakdown',
            name='standard_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakdowns.StandardLibrary'),
        ),
        migrations.AddField(
            model_name='librarybreakdown',
            name='unit',
            field=models.ForeignKey(help_text='Measurement unit for the cost breakdown', on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Unit'),
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='activity_catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdowns.ActivityCatagory'),
        ),
        migrations.AddField(
            model_name='standardlibrary',
            name='library_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='breakdowns.LibraryPackage'),
        ),
    ]
