# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0051_auto_20180125_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbreakdown',
            name='rental_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Equipment hourly rental rate', max_digits=8),
        ),
    ]
