# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0052_auto_20180125_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activated',
            field=models.BooleanField(default=True, verbose_name='Activated Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='Primary project'),
        ),
    ]
