# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0053_auto_20180126_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Project catagories',
                'ordering': ['full_title'],
            },
        ),
    ]
