# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0054_projectcatagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='breakdowns.ProjectCatagory'),
            preserve_default=False,
        ),
    ]
