# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-27 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0055_project_project_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costbreakdown',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdowns.Project'),
        ),
        migrations.AlterField(
            model_name='standardlibrary',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='standardlibrary',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='First Published'),
        ),
    ]
