# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-27 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0056_auto_20180127_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardlibrary',
            name='remark',
        ),
        migrations.AddField(
            model_name='standardlibrary',
            name='rating',
            field=models.IntegerField(default=0, help_text='Rating of the breakdown from 0 to 5'),
        ),
    ]
